### ISSUE TITLE
ArduPilotManager not starting on Navigator

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#171]
This is returned from the container:

```bash
root@companion:/# /home/pi/services/ardupilot_manager/main.py
Loaded settings from /root/.config/ardupilot-manager/settings.json:
{}
Traceback (most recent call last):
  File "/home/pi/services/ardupilot_manager/main.py", line 49, in <module>
    autopilot.run()
  File "/home/pi/services/ardupilot_manager/ArduPilotManager.py", line 39, in run                                                                            
    while not self.start_board(BoardDetector.detect()):
  File "/home/pi/services/ardupilot_manager/ArduPilotManager.py", line 103, in start_board                                                                   
    self.start_navigator()
  File "/home/pi/services/ardupilot_manager/ArduPilotManager.py", line 55, in start_navigator                                                                
    os.rename(temporary_file, firmware)
OSError: [Errno 18] Invalid cross-device link: '/tmp/czjfwdyqpktusebv-ardusub' -> '/root/.config/ardupilot-manager/firmware/ardusub'
```

**Comment by rafaellehmkuhl** [comment]
@jaxxzer it's the first time I use APManager with the Navigator. Have you seen this before?

**Comment by patrickelectric** [comment]
It appears that is something related to how os.rename works, doing a simlink or hardlink between two different devices, I would recommend to use move.

**Comment by jaxxzer** [comment]
https://github.com/bluerobotics/companion-docker/pull/136 will fix it

**Comment by jaxxzer** [comment]
Duplicate #135
