### ISSUE TITLE
bootstrap: broken dependency `six`

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/companion-docker#241]
```
deleted: sha256:251c6f26ad2a31fcf30f743d67152e727596d67c3c75bb43cd4460090d9ca8fd
deleted: sha256:1d8d318946a41ddc0408af69ef0db5f95dba751942b343559a253380df9c0759

Total reclaimed space: 765.4MB
Going to install companion-docker version master.
Downloading and installing udev rules.
Downloading bootstrap
master: Pulling from bluerobotics/companion-bootstrap
3035777cd90a: Pull complete 
40660309407b: Pull complete 
7d0b89f323bf: Pull complete 
3f1ca49b9100: Pull complete 
78c960870bce: Pull complete 
Digest: sha256:a11b2dc1ab43f51bc7d3c1c93879ac67425348979cfef96af917901e586f58a9
Status: Downloaded newer image for bluerobotics/companion-bootstrap:master
docker.io/bluerobotics/companion-bootstrap:master
Traceback (most recent call last):
  File "/main.py", line 6, in <module>
    import docker
  File "/usr/local/lib/python3.7/dist-packages/docker-5.0.0-py3.7.egg/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.7/dist-packages/docker-5.0.0-py3.7.egg/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.7/dist-packages/docker-5.0.0-py3.7.egg/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/usr/local/lib/python3.7/dist-packages/docker-5.0.0-py3.7.egg/docker/auth.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by patrickelectric** [comment]
It appears that docker dependency has not a fixed version, it appears to be the root of the problem:
https://github.com/bluerobotics/companion-docker/blob/master/bootstrap/bootstrap/setup.py#L11
